from pydantic import BaseModel, Field
from typing import List, Dict, Any

# ==========================================
# 1. Pydantic Validation Models
# ==========================================

class CurriculumModel(BaseModel):
    """
    Validates the structure of the JSON curriculum generated by the Architect Agent.
    If the LLM hallucinates a bad schema, Pydantic catches it here.
    """
    title: str = Field(..., description="The main title of the learning path")
    modules: List[str] = Field(..., description="A list of sequential learning steps")
    search_queries: List[str] = Field(..., description="Queries used by the Librarian tool")

# ==========================================
# 2. SQLite DDL (Data Definition Language)
# ==========================================

# By isolating the SQL strings here, your crud.py file only handles execution logic.
CREATE_LEARNING_PATHS_TABLE = """
CREATE TABLE IF NOT EXISTS learning_paths (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    goal TEXT NOT NULL,
    curriculum JSON,
    resources JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""