from pydantic import BaseModel, Field
from typing import List

# ==========================================
# 1. Pydantic Validation Models
# ==========================================

class CurriculumModel(BaseModel):
    """
    Validates the structure of the JSON curriculum generated by the Architect Agent.
    We pass this schema directly to the Gemini API to guarantee the output format.
    """
    title: str = Field(..., description="The main title of the learning path")
    modules: List[str] = Field(..., description="A list of sequential learning steps for the topic")
    search_queries: List[str] = Field(..., description="Precise YouTube search queries to find tutorials for these modules")

# ==========================================
# 2. SQLite DDL (Data Definition Language)
# ==========================================

# By isolating the SQL strings here, your db/crud.py file only handles execution logic.
CREATE_LEARNING_PATHS_TABLE = """
CREATE TABLE IF NOT EXISTS learning_paths (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    goal TEXT NOT NULL,
    curriculum JSON,
    resources JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""