from core.state import NotschoolState
from tools.youtube_client import search_youtube_videos

def librarian_node(state: NotschoolState) -> dict:
    """
    Acts as the Resource Curator. 
    Reads the curriculum generated by the Architect and fetches relevant YouTube URLs.
    """
    curriculum = state.get("curriculum_json")
    
    # Defensive programming: If the architect failed, fallback to the generic goal
    if not curriculum or not curriculum.get("search_queries"):
        queries = [state["goal"]]
    else:
        queries = curriculum["search_queries"]

    # Call the isolated API tool built by the API Lead
    urls = search_youtube_videos(queries=queries, max_results_per_query=1)

    return {
        "youtube_urls": urls,
        "messages": [{"role": "system", "content": f"Librarian successfully fetched {len(urls)} video resources."}]
    }