from core.state import NotschoolState
from tools.youtube_client import search_youtube_videos

def librarian_node(state: NotschoolState) -> dict:
    """
    Reads the curriculum generated by the architect and fetches 
    relevant video resources using the YouTube tool.
    """
    curriculum = state.get("curriculum_json", {})
    queries = curriculum.get("search_queries", [])
    
    # Fallback if the architect failed to generate queries
    if not queries:
        queries = [state["goal"]]

    # Call the isolated tool
    urls = search_youtube_videos(queries=queries, max_results_per_query=1)

    return {
        "youtube_urls": urls,
        "messages": [{"role": "system", "content": f"Librarian found {len(urls)} video resources."}]
    }